apiVersion: v2
appVersion: 0.4.0
description: A Helm chart to provision standard workloads using score-helm. This chart can be forked and adapted for other use cases.
name: workload
type: application
version: 0.4.0
